import type { AnalysisContext, Detector, TransactionIntent } from "./types.js";

function circuitKey(intent: TransactionIntent): string {
  return `${intent.contractAddress}:${intent.circuitId}`;
}

/** Blind sign risk: flags an unknown contract+circuit combination. */
export const blindSignRisk: Detector = (intent, ctx) => {
  if (ctx.knownCircuits.has(circuitKey(intent))) return null;
  return {
    id: "blind-sign",
    severity: "critical",
    title: "Unknown contract call",
    detail: `The circuit "${intent.circuitId}" at ${intent.contractAddress} is not on the approved list. Don't sign without verifying what it does.`,
  };
};

/** Unlimited approval risk: flags calls requesting unlimited/excessive spend authority. */
export const unlimitedApprovalRisk: Detector = (intent) => {
  if (intent.circuitId !== "setPolicy") return null;
  const cap = intent.args.newCapPerTx;
  if (typeof cap !== "number") return null;
  const UNREASONABLY_HIGH = 1_000_000_000;
  if (cap >= UNREASONABLY_HIGH) {
    return {
      id: "unlimited-approval",
      severity: "critical",
      title: "Near-unlimited spending cap requested",
      detail: `This policy requests spending authority of up to ${cap} units per transaction — effectively unlimited approval.`,
    };
  }
  return null;
};

/** Agentic x402 risk: an AI agent making a micro-payment without direct user approval. */
export const agenticX402Risk: Detector = (intent) => {
  if (intent.initiator !== "agent") return null;
  if (intent.circuitId !== "authorizeSpend") return null;
  return {
    id: "agentic-x402",
    severity: "warning",
    title: "Autonomous agent payment",
    detail: "This payment was triggered by an automated agent, not a human. Review it even if it stays within policy limits.",
  };
};

/** Balance delta summary: summarizes the simulated balance change. */
export const balanceDeltaSummary: Detector = (_intent, ctx) => {
  const meaningful = ctx.balanceDeltas.filter((d) => d.before !== d.after);
  if (meaningful.length === 0) return null;
  const lines = meaningful
    .map((d) => `${d.asset}: ${d.before} → ${d.after}`)
    .join(", ");
  return {
    id: "balance-delta",
    severity: "info",
    title: "Balance change",
    detail: lines,
  };
};

/** Contract interaction trace: chained contract-to-contract calls. */
export const contractInteractionTrace: Detector = (_intent, ctx) => {
  if (ctx.calledContracts.length === 0) return null;
  return {
    id: "contract-interactions",
    severity: "info",
    title: "Chained contract calls",
    detail: `This transaction also calls: ${ctx.calledContracts.join(", ")}`,
  };
};

/** NEW (Midnight-specific): witness data disclosed to the public ledger via disclose(). */
export const disclosureRisk: Detector = (intent) => {
  const witnessDisclosures = intent.disclosures.filter((d) => d.source === "witness");
  if (witnessDisclosures.length === 0) return null;
  const fields = witnessDisclosures.map((d) => d.field).join(", ");
  return {
    id: "disclosure",
    severity: "warning",
    title: "Private data is being disclosed",
    detail: `This transaction writes the following private (witness) fields to the public ledger: ${fields}. Once signed, this information becomes public.`,
  };
};

/** NEW (Midnight-specific): notice for whether the proof is generated locally or delegated. */
export const provingModeNotice: Detector = (intent) => {
  if (intent.provingMode !== "delegated") return null;
  return {
    id: "proving-mode",
    severity: "info",
    title: "Proof generation delegated",
    detail: "This transaction's ZK proof will be generated by an external proof server, not on your own device.",
  };
};

/** Policy-based spend limit check (per-transaction / per-day cap). */
export const spendPolicyLimitRisk: Detector = (intent, ctx) => {
  if (intent.circuitId !== "authorizeSpend" || !ctx.policy) return null;
  const amount = intent.args.amount;
  if (typeof amount !== "number") return null;
  const { policy } = ctx;

  if (policy.status !== "ACTIVE") {
    return {
      id: "policy-inactive",
      severity: "critical",
      title: "Policy is not active",
      detail: `Policy status is "${policy.status}". This transaction would already be rejected by the contract.`,
    };
  }
  if (BigInt(amount) > policy.capPerTx) {
    return {
      id: "over-per-tx-cap",
      severity: "critical",
      title: "Per-transaction cap exceeded",
      detail: `Requested amount (${amount}) exceeds the per-transaction cap (${policy.capPerTx}).`,
    };
  }
  if (policy.spentThisPeriod + BigInt(amount) > policy.capPerDay) {
    return {
      id: "over-per-day-cap",
      severity: "critical",
      title: "Daily cap exceeded",
      detail: `Amount spent this period (${policy.spentThisPeriod}) plus requested (${amount}) exceeds the daily cap (${policy.capPerDay}).`,
    };
  }
  return null;
};

export const allDetectors: Detector[] = [
  blindSignRisk,
  unlimitedApprovalRisk,
  agenticX402Risk,
  spendPolicyLimitRisk,
  balanceDeltaSummary,
  contractInteractionTrace,
  disclosureRisk,
  provingModeNotice,
];
